### ISSUE TITLE
Release fails with electron-packager 5.1.0

### ISSUE THREAD

**Issue by domasx2** [chentsulin/electron-react-boilerplate#43]
Hi,

Releases pacakged with electron-packager 5.1.0 don't run:

```
Error: Cannot find module '/home/domas/Projects/electron-react-boilerplate/release/linux-x64/ElectronReact-linux-x64/resources/atom.asar/browser/lib/init.js'
```

But works with 5.0.2. Fixed the problem for me by updating package.json to fixed vesion of electron-packager:
`"electron-packager": "=5.0.2"`

Not sure yet why 5.1.0 broke

**Comment by chentsulin** [comment]
I can't reproduce this on my computer with electron-packager 5.1.0 installed. Could you provide precise reproduce steps and your os environment information?

**Comment by domasx2** [comment]
3 days ago it would fail the same on ubuntu 15.04 and a macbook.

I tried to reproduce it from scratch again to paste you console output, but it works now with 5.1.0, strange... Something must have changed since.

Can close this then, I guess :)

**Comment by chentsulin** [comment]
Maybe one of electron-packager's dependencies apply the patch. Anyway, reopen this if you reproduce this issue.
